source "https://rubygems.org"

# Specify your gem's dependencies in sahih_muslim.gemspec
gemspec

gem "rake", "~> 13.0"
gem "minitest", "~> 5.0"

# Development dependencies
group :development, :test do
  gem "pry"
  gem "rubocop"
end
