require "bundler/gem_tasks"
require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

task default: :test

# Add custom tasks for data processing
namespace :sahih_muslim do
  desc "Process hadith data files"
  task :process_data do
    ruby "lib/sahih_muslim/data_processor.rb"
  end

  desc "Validate hadith data integrity"
  task :validate_data do
    ruby "lib/sahih_muslim/validator.rb"
  end
end
